### ISSUE TITLE
Utf8 folder names

### ISSUE THREAD

**Issue by sergeymild** [michaelspiss/imap_client#15]
For example i have Russian folder name(it doesn't matter which language but not English) and when i fetch list of folders i received something like this: &BD4EPwQ7BDAEQgRLAKAENwQwAKAEOgQy-
instead of folder name.
I know that it a modified utf-7 encoding.
i found some libraries on JavaScript https://github.com/emailjs/emailjs-utf7
how they parsing that.

**Comment by sergeymild** [comment]
What does mean this tag? Sorry i don't understand)

**Comment by michaelspiss** [comment]
This is part of the imap standard ([section 5.1.3](https://tools.ietf.org/html/rfc3501#section-5.1.3)) and should definitely be supported by this package.

Todo:
- [x] Convert international utf-7 folder names to utf-8 strings
- [x] On folder rename, replace utf-8 characters with utf-7 representation
- [x] On folder creation, replace utf-8 characters with utf-7 representation
