### ISSUE TITLE
How to login use xoauth2?

### ISSUE THREAD

**Issue by pewh** [michaelspiss/imap_client#17]
My use case is user login without asking password from app. What I need is to use google_sign_in instead. But how I passing xoauth2 token to imap_client?

**Comment by michaelspiss** [comment]
I haven't implemented oauth yet, but you can write your own authentication mechanism as described [on this wiki page](https://github.com/michaelspiss/imap_client/wiki/Create-custom-SASL-(authentication)-mechanism). It can then be passed to the `authenticate()` method.
