### ISSUE TITLE
Error parsing mail with pgp attachment

### ISSUE THREAD

**Issue by t0mmar** [michaelspiss/imap_client#18]
**Bug description**
Throws an exception when doing FETCH of BODYSTRUCTURE of a pgp-encrypted message

**To Reproduce**
Use gpg and Thunderbird to encrypt and sign a message and then attempt to FETCH its BODYSTRUCTURE.

**Expected behavior**
Successfully parses BODYSTRUCTURE response without exceptions.

**Additional context**

Exception is thrown in _processBodyMultiPart:

```
  static Future<Map<String, dynamic>> _processBodyMultiPart(
      ImapBuffer buffer) async {
    Map<String, dynamic> results = {"BODIES": <Map<String, dynamic>>[]};
    ImapWord word = await buffer.readWord();
    while (word.type == ImapWordType.parenOpen) {
      buffer.unread(word.value);
      results["BODIES"].add(await _processBody(buffer));
      word = await buffer.readWord();
    }
    if (word.type != ImapWordType.string) {
      throw new SyntaxErrorException("Expected string, but got $word"); <<<--- HERE
    }
```

word.type == ImapWordType.nil at this point

Log:
```
flutter: [INFO] imap_client: C: A7 FETCH 1 (BODYSTRUCTURE)
flutter: [INFO] imap_client: S: * 1 FETCH (BODYSTRUCTURE (("application" "pgp-encrypted" NIL NIL NIL "quoted-printable" 10 NIL NIL NIL NIL)("application" "octet-stream" ("name" "encrypted.asc") NIL NIL "7bit" 2871 NIL ("inline" ("filename" "encrypted.asc")) NIL NIL) "encrypted" ("boundary" "----KV1DHT7MP87IMFT410O4TDRRPM94YK" "protocol" "application/pgp-encrypted") NIL NIL NIL))

A7 OK Fetch completed (0.001 + 0.000 secs).
```

**Comment by michaelspiss** [comment]
Thanks for reporting this bug. Seems like this has the same cause as #16. I will rewrite the bodystructure parser in the (near-ish) future, but don't have a lot of spare time at the moment. Pull requests are welcome if you find the bug!
