### ISSUE TITLE
[flutter_imap_mail] flutter packages get

### ISSUE THREAD

**Issue by aliheader** [michaelspiss/imap_client#22]
[flutter_imap_mail] flutter packages get
Running "flutter pub get" in flutter_imap_mail...               
Because every version of flutter_test from sdk depends on pedantic 1.8.0+1 and imap_client >=0.2.8 <1.0.0-alpha depends on pedantic ^1.9.0, flutter_test from sdk is incompatible with imap_client >=0.2.8 <1.0.0-alpha.

So, because flutter_imap_mail depends on both imap_client ^0.2.8 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because flutter_imap_mail depends on both imap_client ^0.2.8 and flutter_test any from sdk, version solving failed.)
exit code 1

**Comment by michaelspiss** [comment]
Fixed with version 0.2.9
