### ISSUE TITLE
trigger on incoming new un-read messages

### ISSUE THREAD

**Issue by Jefry-nolastname** [michaelspiss/imap_client#23]
hi , first of all thank you so much on building this wonderful imap plugin.
my email app is almost finish but i can't wrap my head around how to show notification on new incoming message. my first thought is to use android_alarm_manager plugin to count unread messages in inbox periodically and save it to shared preferences. If the amount of unread msg different from the previous one (shared preferences) it show notification with mail content at the top of mail box. But it felt unsafe as there're many factor that could modify mail length in mailbox, like moving,deleting mail for example. 
i was wondering can you at least guide me to the right direction on how to properly use imap protocol for this to achieve my goal as i'm very new with it, thankyou,

**Comment by Jefry-nolastname** [comment]
hi again, just read about the existance of mail with /recent flag but when i tried calling fetch on RECENT it always return null. Sorry again for bothering you

**Comment by michaelspiss** [comment]
You could simply remember the uidnext (next unique id of a  message, set by the imap server) value when selecting a folder:
```dart
import 'package:imap_client/imap_client.dart';

main() async {
  ImapClient client = new ImapClient();
  
  await client.connect("imap.gmail.com", 993, true);
  
  ImapFolder inbox = client.getFolder("inbox");

  int uidnext = inbox.uidnext;
}
```
If this value changed, at least one new message arrived

**Comment by Jefry-nolastname** [comment]
hi again haha 
i tried to print the value of the uidnext.
it seems the value only change when you completely reconnect to mailserver and so i think using recent flag would be better in this situation based on it only need refetching the imap folder.
And your code is fine, it was my bad code that return null when i tried to search the flag /RECENT

[checknewMail.txt](https://github.com/michaelspiss/imap_client/files/4655908/checknewMail.txt)

btw i was wondering, is there a way to search /RECENT in all folder(spam folder ex,) at once via imap protocol  or the only way is to loop through all folder? i tried searching from root but it returns null.

**Comment by Jefry-nolastname** [comment]
btw the issue is done. i'll close it tommorow at work. thank a bunch

**Comment by michaelspiss** [comment]
Yes, uidnext is updated on folder selection, but also when a `noop` command is issued. If what you are looking for are real-time notifications you might want to check out the `idle` command, which automatically updates a folder's mailCount and recentCount.
The imap protocol treats each folder separately, so there is no easy way to fetch all /RECENT messages without looping through the folders.
I will leave this open for you to close if you have further questions.

**Comment by Jefry-nolastname** [comment]
thanks a bunch ^^ awesome plugin

**Comment by michaelspiss** [comment]
Glad I could help
