### ISSUE TITLE
Folder "inbox" could not be selected.

### ISSUE THREAD

**Issue by Youcef-Goudjal** [michaelspiss/imap_client#24]
error:
I/flutter (14520): Folder "inbox" could not be selected.
E/flutter (14520): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Expected */+/TAG, but got [Word ImapWordType.flag] \Draft
E/flutter (14520): #0      ImapCommand.run (package:imap_client/src/imap_command.dart:103:9)
E/flutter (14520): <asynchronous suspension>
E/flutter (14520): #1      ImapEngine.executeCommand (package:imap_client/src/imap_engine.dart:110:33)
E/flutter (14520): <asynchronous suspension>
E/flutter (14520): #2      _ImapCommandable.getFolder (package:imap_client/src/imap_commandable.dart:138:19)
E/flutter (14520): #3      _HomeState.getEmails (package:mail_app/main.dart:49:10)
E/flutter (14520): #4      _HomeState.build.<anonymous closure> (package:mail_app/main.dart:61:11)
E/flutter (14520): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (14520): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (14520): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (14520): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (14520): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (14520): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
E/flutter (14520): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
E/flutter (14520): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
E/flutter (14520): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
E/flutter (14520): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (14520): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
E/flutter (14520): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
E/flutter (14520): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter (14520): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (14520): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (14520): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (14520): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (14520): #22     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (14520): #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (14520): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (14520): #25     _invoke1 (dart:ui/hooks.dart:283:10)
E/flutter (14520): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:192:5)
E/flutter (14520): 

code:
`Future<List> getEmails()async{
    try {
      ImapFolder inbox = await client.getFolder("inbox");
    }catch(e){
      print(e.toString());
    }
...
  }`

**Comment by michaelspiss** [comment]
Please include the log data, I can't help you otherwise. Logs can be viewed by calling printImapClientDebugLog() before any other methods. Also, which server are you trying to connect to?

**Comment by Youcef-Goudjal** [comment]
I'm trying to connect to gmail 
await client.connect("imap.gmail.com", 993, true);
output:
I/flutter (16447): [INFO] imap_client: C: A4 SELECT "inbox"
I/flutter (16447): [INFO] imap_client: S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584
I/flutter (16447): A2 OK m.*******@gmail.com authenticated (Success)
E/flutter (16447): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Trying to use "SELECT/EXAMINE" in unauthenticated state.
E/flutter (16447): #0      _ImapCommandable._requiresAuthenticated (package:imap_client/src/imap_commandable.dart:351:7)
E/flutter (16447): #1      _ImapCommandable.getFolder.<anonymous closure> (package:imap_client/src/imap_commandable.dart:136:29)
E/flutter (16447): #2      ImapEngine.executeCommand (package:imap_client/src/imap_engine.dart:104:42)
E/flutter (16447): <asynchronous suspension>
E/flutter (16447): #3      _ImapCommandable.getFolder (package:imap_client/src/imap_commandable.dart:138:19)
E/flutter (16447): #4      _HomeState.getEmails (package:mail_app/main.dart:50:10)
E/flutter (16447): #5      _HomeState.build.<anonymous closure> (package:mail_app/main.dart:62:11)
E/flutter (16447): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (16447): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (16447): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (16447): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (16447): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (16447): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
E/flutter (16447): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
E/flutter (16447): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
E/flutter (16447): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
E/flutter (16447): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (16447): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
E/flutter (16447): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
E/flutter (16447): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter (16447): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (16447): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (16447): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (16447): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (16447): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (16447): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (16447): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (16447): #26     _invoke1 (dart:ui/hooks.dart:283:10)
E/flutter (16447): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:192:5)
E/flutter (16447): 
I/flutter (16447): [INFO] imap_client: S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
I/flutter (16447): * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
I/flutter (16447): * OK [UIDVALIDITY 1] UIDs valid.
I/flutter (16447): * 2 EXISTS
I/flutter (16447): * 0 RECENT
I/flutter (16447): * OK [UIDNEXT 17] Predicted next UID.
I/flutter (16447): * OK [HIGHESTMODSEQ 2751]
I/flutter (16447): A4 OK [READ-WRITE] inbox selected. (Success)

**Comment by michaelspiss** [comment]
It seems like you are trying to select the folder before you are fully authenticated. Make sure to `await` each command you send to the server. In your case I suspect a missing `await` in front of `client.login(...)` or `client.authenticate(...)`
