### ISSUE TITLE
Can't analysis Chinese 

### ISSUE THREAD

**Issue by zhangxinagjunHJH** [michaelspiss/imap_client#25]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by michaelspiss** [comment]
Hi, please provide more information.

What are you trying to do?
How are you trying to do it?
What happens?
What does the log say?

Thanks

**Comment by zhangxinagjunHJH** [comment]
@michaelspiss Thank you for your reply so quickly. I found one problem if the email content contains Chinese fields, it will give this words, such as "Department":"=E6=9C=AC=E5=8D=95=E4=BD=8D". Then I checked the email in my Imap account, it's correct, it shows "Department":"本单位".
So I think these are the problems of decoding Chinese fields?

**Comment by michaelspiss** [comment]
"=E6=9C=AC=E5=8D=95=E4=BD=8D" is the encoded representation of "本单位", as imap (without utf8 extension) only works with us-ascii characters. So this is actually working as expected. This package does not include a mime parser which would convert it back to human-readable format.

Decoding "quoted printable" encoded strings basically works by splitting the string at each `=` and then treating all substrings as hexadecimals. They can be converted into integers with `int.parse("0x$hex");` (hex being the variable holding a substring). Put all (now) decimals into an array and decode it using `utf8.decode(array_of_integers);`. This gives you the string in readable form.

**Comment by zhangxinagjunHJH** [comment]
@michaelspiss Yes, I checked the encode format, then converted it to readable format.
