### ISSUE TITLE
Fetching email in web browser giving Raw socket constructor error

### ISSUE THREAD

**Issue by saqib556612** [michaelspiss/imap_client#27]
Debug service listening on ws://127.0.0.1:60991/6cwe7-gG74Y=
Debug service listening on ws://127.0.0.1:60991/6cwe7-gG74Y=
[INFO] imap_client: Connecting to imap.gmail.com at port 993 with secure mode on
Error: Unsupported operation: RawSocket constructor
    at Object.throw_ [as throw] (http://localhost:60918/dart_sdk.js:4328:11)
    at Function.connect (http://localhost:60918/dart_sdk.js:57912:17)
    at Function.connect (http://localhost:60918/dart_sdk.js:56048:27)

if any other method for fetching emails from mail account. please suggest me as well

**Comment by michaelspiss** [comment]
RawSockets don't exist in web browsers, which is why you get this warning. I'm currently not planning on adding web support, but feel free to fork and replace the "normal" socket with a websocket!
