### ISSUE TITLE
Decode Header Fields

### ISSUE THREAD

**Issue by Tienisto** [michaelspiss/imap_client#28]
**Is your feature request related to a problem? Please describe.**
Sometimes the header value is decoded something like this:
`[personal-l] =?utf-8?q?Neue_hochschul=C3=B6ffentliche_Bekanntmac?= =?utf-8?q?hung?=`
I am trying to decode the header by myself but it is not very easy.

**Describe the solution you'd like**
The library should decode it before I get it.
Or at least create a utility function for that so that developers using this library don't need to solve this (unnecessary) problem.

**Describe alternatives you've considered**
No idea.

**Additional context**
Was fetching using `ENVELOPE`, then `map["ENVELOPE"]["subject"]`

**Comment by michaelspiss** [comment]
Hi, encoding/decoding the content of messages is out of the scope for this package, but the encoding is called "quoted printable". You should find information about how to decode it online
