### ISSUE TITLE
Can't login to GMail w/ valid credentials

### ISSUE THREAD

**Issue by bartonhammond** [michaelspiss/imap_client#29]
**Bug description**

Can not successfully log in to GMail.  I use `r` because I have an embedded dollar sign.
```
import 'dart:io';
import 'package:imap_client/imap_client.dart';
Future<void> main() async {
  // print log, helpful for debugging
  printImapClientDebugLog();
  var client = ImapClient();
  // connect
  await client.connect('imap.gmail.com', 993, true);
  // authenticate
  final response = await client.authenticate(
      ImapPlainAuth('bxxxxx@gmail.com', r'''xxxxxx$xxxxx'''));

  if (response != ImapTaggedResponse.ok) {
    exit(1);
  }
```

**To Reproduce**
Step by step description on how to reproduce the error, including log data if possible.
Logs can be viewed by calling printImapClientDebugLog() before any other methods.
```
Connecting to VM Service at ws://127.0.0.1:61858/OZJLHoO_NOc=/ws
[INFO] imap_client: Connecting to imap.gmail.com at port 993 with secure mode on
[INFO] imap_client: S: * OK Gimap ready for requests from 24.183.26.195 135mb86127829ybd
[INFO] imap_client: C: A1 CAPABILITY
[INFO] imap_client: S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
A1 OK Thats all she wrote! 135mb86127829ybd
[INFO] imap_client: C: A2 AUTHENTICATE PLAIN
[INFO] imap_client: S: +
[INFO] imap_client: C: AGJhcnRvbmhhbW1vbmRAZ21haWwuY29tAGIzSlZLUnlWQ28kXlo2
[INFO] imap_client: S: A2 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)
Exited (1)
```

**Expected behavior**
To successfully log in to GMail

**Additional context**

**Comment by michaelspiss** [comment]
Hi, r'...' tells dart to treat the text as a regular expression. You can escape special characters with a backslash: 'xxxx\\$xxxx'. Other than that I cannot see any apparent mistakes.

**Comment by bartonhammond** [comment]
My understanding is that `r` is `raw string`.  From https://www.learndartprogramming.com/fundamentals/strings-and-raw-strings-in-dart/
Maybe I'm confused, but I don't think so (at least, at this moment)
```
Defining raw Strings in Dart
What is a raw strings in Dart: In Dart programming language, raw strings are a type of strings where special characters such as \ do not get special treatment.

Raw strings are useful when you want to define a String that has a lot of special characters.
```

**Comment by michaelspiss** [comment]
Wrong language, my bad - you are correct. Your code seems to be equal to the [example](https://github.com/michaelspiss/imap_client/blob/master/example/example.dart) which has been tested with gmail, so it should be alright...

**Comment by bartonhammond** [comment]
I created a Google account with userid/password shown below.  It still fails.  You can try this code
```
import 'dart:io';

import 'package:imap_client/imap_client.dart';

Future<void> main() async {
  // print log, helpful for debugging
  printImapClientDebugLog();

  var client = ImapClient();
  // connect
  await client.connect('imap.gmail.com', 993, true);
  // authenticate
  final response = await client.authenticate(
      ImapPlainAuth('vijopot950@gmail.com', r'ujbzZ4uhmd'));

  print('reponse ok? ${response == ImapTaggedResponse.ok}');
  if (response != ImapTaggedResponse.ok) {
    exit(1);
  }
  // get folder
  var inbox = await client.getFolder('Inbox');
  // get "BODY" for message 1
  print(await inbox.fetch(['BODY'], messageIds: [1]));
  // get "BODYSTRUCTURE" for message 1
  print(await inbox.fetch(['BODYSTRUCTURE'], messageIds: [1]));
  // close connection
  await client.logout();
}```

Logs:
```
dart bin/emailTest.dart 
[INFO] imap_client: Connecting to imap.gmail.com at port 993 with secure mode on
[INFO] imap_client: S: * OK Gimap ready for requests from 24.183.26.195 j10mb205926323jam

[INFO] imap_client: C: A1 CAPABILITY

[INFO] imap_client: S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
A1 OK Thats all she wrote! j10mb205926323jam

[INFO] imap_client: C: A2 AUTHENTICATE PLAIN

[INFO] imap_client: S: + 

[INFO] imap_client: C: AHZpam9wb3Q5NTBAZ21haWwuY29tAHVqYnpaNHVobWQ=

[INFO] imap_client: S: A2 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)

reponse ok? false
```

**Comment by michaelspiss** [comment]
Did you [enable imap](https://support.google.com/mail/answer/7126229?hl=en) in gmail's options? Other than that I really cannot see why this shouldn't work

**Comment by bartonhammond** [comment]
When I went to check the Google Settings, I was prompted with warning that a call from an unsecure app had been blocked because it didn't meet the standards Google has.  It asked if the block was correct or if I were the person trying to access the account.  Once I replied that I was blocked, it took me through these screens about reducing the security.  Sorry I didn't get a picture of the first dialog.

![Screen Shot 2020-12-17 at 9 21 21 AM](https://user-images.githubusercontent.com/1282364/102507081-771b4c00-4049-11eb-9f04-2575e392ba19.png)

So I updated 
![Screen Shot 2020-12-17 at 9 21 55 AM](https://user-images.githubusercontent.com/1282364/102507116-81d5e100-4049-11eb-9d3b-2e629465ae02.png)

And now it works:
```
mailTest]$ dart bin/emailTest.dart 
[INFO] imap_client: Connecting to imap.gmail.com at port 993 with secure mode on
[INFO] imap_client: S: * OK Gimap ready for requests from 24.183.26.195 q187mb93813797ywf

[INFO] imap_client: C: A1 CAPABILITY

[INFO] imap_client: S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
A1 OK Thats all she wrote! q187mb93813797ywf

[INFO] imap_client: C: A2 AUTHENTICATE PLAIN

[INFO] imap_client: S: + 

[INFO] imap_client: C: AHZpam9wb3Q5NTBAZ21haWwuY29tAHVqYnpaNHVobWQ=

[INFO] imap_client: S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584
A2 OK vijopot950@gmail.com authenticated (Success)
```
