### ISSUE TITLE
Cannot connect to email server

### ISSUE THREAD

**Issue by barilki** [michaelspiss/imap_client#30]
E/flutter ( 3514): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter ( 3514): 	CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:354))

**Comment by michaelspiss** [comment]
This is not a bug, but intentional. The error tells us that there is a self-signed certificate somewhere in the chain, which compromises the trust in this certificate. If you are the owner of this mail server, I suggest you get a certificate from https://letsencrypt.org/
