### ISSUE TITLE
IMAP Client connected to server but not authenticating

### ISSUE THREAD

**Issue by saqib556612** [michaelspiss/imap_client#31]
I am using IMAP to access emails from outlook. It is connecting to server but not authenticating it.

IMAP Tagged Response is NO

**Comment by michaelspiss** [comment]
Please be aware that this package hasn't been under development for some years now, there may be better alternatives. If you still decide to use it, I'd need the complete log message to help here. You can enable debug logging by calling `printImapClientDebugLog()` before anything else from this package.

**Comment by saqib556612** [comment]
As Microsoft Blocks plain authentication mid of the year so that's why its not authenticating Kindly provide the solution in IMAP and if you don't have solution kindly suggest some alternatives because i am unable to get alternatives.

**Comment by michaelspiss** [comment]
Please provide the logs. The imap server announces which authentication methods they provide.

**Comment by saqib556612** [comment]
```
flutter: [INFO] imap_client: Connecting to imap.outlook.com at port 993 with secure mode on
flutter: [INFO] imap_client: S: * OK The Microsoft Exchange IMAP4 service is ready. [UABSADMAUAAyADUAMABDAEEAMAAwADAAOQAuAEUAVQBSAFAAMgA1ADAALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]


flutter: [INFO] imap_client: C: A1 CAPABILITY


flutter: [INFO] imap_client: S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+

A1 OK CAPABILITY completed.


flutter: [INFO] imap_client: C: A2 LOGIN "I wrote real username " " i wrote real password"


flutter: [INFO] imap_client: S: A2 NO LOGIN failed.


flutter: ImapTaggedResponse.no


```

**Comment by michaelspiss** [comment]
I guess that they restrict their authentication to XOAUTH2. I have not implemented this mechanism yet, but you can create your own following this guide: https://github.com/michaelspiss/imap_client/wiki/Create-custom-SASL-(authentication)-mechanism
