### ISSUE TITLE
Error when opening folder names including spaces

### ISSUE THREAD

**Issue by mathisgerdes** [michaelspiss/imap_client#4]
When listing folders from (e.g.) Gmail, returned names include spaces (e.g. '[Gmail]/All Mail'). Trying to open the folders using these returned Strings as names doesn't work and I have to enclose the names manually with quotation marks. 

This should probably (at least for convenience) work without altering the folder names received from list.

**Comment by michaelspiss** [comment]
You are absolutely right, this is not expected behavior.

Needed changes:
Fix ImapEngine._selectFolder() by adding escaped quotes around folder.name as follows: ```"SELECT/EXAMINE \"" + folder.name + "\""```

I will update as soon as possible, but I won't be able to until the end of next week

**Comment by michaelspiss** [comment]
Fixed in next release after v0.2.0, currently in develop branch
