### ISSUE TITLE
Fetching the envelop fails if the subject line contains quotation marks

### ISSUE THREAD

**Issue by mathisgerdes** [michaelspiss/imap_client#7]
When trying to fetch the envelop of an email with a subject line that contains a quotation mark, an error occurs saying that while scanning the response a close-bracket imap word was expected.

The reason for this seems to be that the email server escapes the quotation mark as `\"`, but this is not recognized by this package at the moment.

**Comment by michaelspiss** [comment]
Fixed by merging #5
